#!/bin/bash
#set -x
#
# Copyright (C) 2013, Roberto C. Morano <rcmova@gmail.com>
# 
# This software is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
#
# As a special exception, if you link this library with other files to
# produce an executable, this library does not by itself cause the
# resulting executable to be covered by the GNU General Public License.
# This exception does not however invalidate any other reasons why the
# executable file might be covered by the GNU General Public License.

TERMINATOR_LAYOUT_NAME="floating-terminator"

pgrep -f -l terminator.*$TERMINATOR_LAYOUT_NAME
if [ $? -ne 0 ]
then
    terminator -l $TERMINATOR_LAYOUT_NAME
	exit 0
fi

MONITOR_NUMBER=$1

WINDOW_PROCESS_PATTERN="terminator.*-l.*$TERMINATOR_LAYOUT_NAME"

WINDOW_PID=$(ps ax|grep $WINDOW_PROCESS_PATTERN|grep -v grep|awk '{print $1}')
WMCTRL_ID=$(wmctrl -lp | grep $WINDOW_PID|awk '{print $1}')
XDOTOOL_ID=$(xdotool search --pid $WINDOW_PID|tail -n1)
XDOTOOL_CURRENT_WINDOW_ID=$(xdotool getwindowfocus)

if [ $XDOTOOL_ID -eq $XDOTOOL_CURRENT_WINDOW_ID ]
then
	xdotool windowminimize $XDOTOOL_ID
else
	wmctrl -iR $WMCTRL_ID
  case "$MONITOR_NUMBER" in
    1)
        # set geometry for monitor 1
        wmctrl -ir $WMCTRL_ID -e 0,0,0,1920,550;;
    2)
        # set geometry for monitor 2
        wmctrl -ir $WMCTRL_ID -e 0,1366,0,1920,550;;
    3)  
        # set geometry for monitor 3
        wmctrl -ir $WMCTRL_ID -e 0,3840,0,1920,500;;
  esac
fi

#   Position: 1377,113 (screen: 0)
#   Geometry: 1918x496
